[profile.default]
src = 'contracts/src'
test = 'contracts/test'
out = 'contracts/out'
libs = ['contracts/lib']
solc = '0.8.20'

optimizer = true
optimizer_runs = 200

gas_limit = 30000000
gas_reports = ["*"]

verbosity = 4

remappings = [
    '@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/',
    '@opengsn/contracts/=node_modules/@opengsn/contracts/',
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
