/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RaiseImport } from './routes/raise'
import { Route as PocketImport } from './routes/pocket'
import { Route as HandsImport } from './routes/hands'
import { Route as IndexImport } from './routes/index'
import { Route as HIdImport } from './routes/h.$id'
import { Route as DevGalleryImport } from './routes/dev.gallery'
import { Route as HIdThankImport } from './routes/h.$id.thank'

// Create/Update Routes

const RaiseRoute = RaiseImport.update({
  id: '/raise',
  path: '/raise',
  getParentRoute: () => rootRoute,
} as any)

const PocketRoute = PocketImport.update({
  id: '/pocket',
  path: '/pocket',
  getParentRoute: () => rootRoute,
} as any)

const HandsRoute = HandsImport.update({
  id: '/hands',
  path: '/hands',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const HIdRoute = HIdImport.update({
  id: '/h/$id',
  path: '/h/$id',
  getParentRoute: () => rootRoute,
} as any)

const DevGalleryRoute = DevGalleryImport.update({
  id: '/dev/gallery',
  path: '/dev/gallery',
  getParentRoute: () => rootRoute,
} as any)

const HIdThankRoute = HIdThankImport.update({
  id: '/thank',
  path: '/thank',
  getParentRoute: () => HIdRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/hands': {
      id: '/hands'
      path: '/hands'
      fullPath: '/hands'
      preLoaderRoute: typeof HandsImport
      parentRoute: typeof rootRoute
    }
    '/pocket': {
      id: '/pocket'
      path: '/pocket'
      fullPath: '/pocket'
      preLoaderRoute: typeof PocketImport
      parentRoute: typeof rootRoute
    }
    '/raise': {
      id: '/raise'
      path: '/raise'
      fullPath: '/raise'
      preLoaderRoute: typeof RaiseImport
      parentRoute: typeof rootRoute
    }
    '/dev/gallery': {
      id: '/dev/gallery'
      path: '/dev/gallery'
      fullPath: '/dev/gallery'
      preLoaderRoute: typeof DevGalleryImport
      parentRoute: typeof rootRoute
    }
    '/h/$id': {
      id: '/h/$id'
      path: '/h/$id'
      fullPath: '/h/$id'
      preLoaderRoute: typeof HIdImport
      parentRoute: typeof rootRoute
    }
    '/h/$id/thank': {
      id: '/h/$id/thank'
      path: '/thank'
      fullPath: '/h/$id/thank'
      preLoaderRoute: typeof HIdThankImport
      parentRoute: typeof HIdImport
    }
  }
}

// Create and export the route tree

interface HIdRouteChildren {
  HIdThankRoute: typeof HIdThankRoute
}

const HIdRouteChildren: HIdRouteChildren = {
  HIdThankRoute: HIdThankRoute,
}

const HIdRouteWithChildren = HIdRoute._addFileChildren(HIdRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hands': typeof HandsRoute
  '/pocket': typeof PocketRoute
  '/raise': typeof RaiseRoute
  '/dev/gallery': typeof DevGalleryRoute
  '/h/$id': typeof HIdRouteWithChildren
  '/h/$id/thank': typeof HIdThankRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hands': typeof HandsRoute
  '/pocket': typeof PocketRoute
  '/raise': typeof RaiseRoute
  '/dev/gallery': typeof DevGalleryRoute
  '/h/$id': typeof HIdRouteWithChildren
  '/h/$id/thank': typeof HIdThankRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/hands': typeof HandsRoute
  '/pocket': typeof PocketRoute
  '/raise': typeof RaiseRoute
  '/dev/gallery': typeof DevGalleryRoute
  '/h/$id': typeof HIdRouteWithChildren
  '/h/$id/thank': typeof HIdThankRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/hands'
    | '/pocket'
    | '/raise'
    | '/dev/gallery'
    | '/h/$id'
    | '/h/$id/thank'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/hands'
    | '/pocket'
    | '/raise'
    | '/dev/gallery'
    | '/h/$id'
    | '/h/$id/thank'
  id:
    | '__root__'
    | '/'
    | '/hands'
    | '/pocket'
    | '/raise'
    | '/dev/gallery'
    | '/h/$id'
    | '/h/$id/thank'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HandsRoute: typeof HandsRoute
  PocketRoute: typeof PocketRoute
  RaiseRoute: typeof RaiseRoute
  DevGalleryRoute: typeof DevGalleryRoute
  HIdRoute: typeof HIdRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HandsRoute: HandsRoute,
  PocketRoute: PocketRoute,
  RaiseRoute: RaiseRoute,
  DevGalleryRoute: DevGalleryRoute,
  HIdRoute: HIdRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/hands",
        "/pocket",
        "/raise",
        "/dev/gallery",
        "/h/$id"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/hands": {
      "filePath": "hands.tsx"
    },
    "/pocket": {
      "filePath": "pocket.tsx"
    },
    "/raise": {
      "filePath": "raise.tsx"
    },
    "/dev/gallery": {
      "filePath": "dev.gallery.tsx"
    },
    "/h/$id": {
      "filePath": "h.$id.tsx",
      "children": [
        "/h/$id/thank"
      ]
    },
    "/h/$id/thank": {
      "filePath": "h.$id.thank.tsx",
      "parent": "/h/$id"
    }
  }
}
ROUTE_MANIFEST_END */
