/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RaiseImport } from './routes/raise'
import { Route as IndexImport } from './routes/index'
import { Route as HIdImport } from './routes/h.$id'
import { Route as HIdThankImport } from './routes/h.$id.thank'

// Create/Update Routes

const RaiseRoute = RaiseImport.update({
  id: '/raise',
  path: '/raise',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const HIdRoute = HIdImport.update({
  id: '/h/$id',
  path: '/h/$id',
  getParentRoute: () => rootRoute,
} as any)

const HIdThankRoute = HIdThankImport.update({
  id: '/thank',
  path: '/thank',
  getParentRoute: () => HIdRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/raise': {
      id: '/raise'
      path: '/raise'
      fullPath: '/raise'
      preLoaderRoute: typeof RaiseImport
      parentRoute: typeof rootRoute
    }
    '/h/$id': {
      id: '/h/$id'
      path: '/h/$id'
      fullPath: '/h/$id'
      preLoaderRoute: typeof HIdImport
      parentRoute: typeof rootRoute
    }
    '/h/$id/thank': {
      id: '/h/$id/thank'
      path: '/thank'
      fullPath: '/h/$id/thank'
      preLoaderRoute: typeof HIdThankImport
      parentRoute: typeof HIdImport
    }
  }
}

// Create and export the route tree

interface HIdRouteChildren {
  HIdThankRoute: typeof HIdThankRoute
}

const HIdRouteChildren: HIdRouteChildren = {
  HIdThankRoute: HIdThankRoute,
}

const HIdRouteWithChildren = HIdRoute._addFileChildren(HIdRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/raise': typeof RaiseRoute
  '/h/$id': typeof HIdRouteWithChildren
  '/h/$id/thank': typeof HIdThankRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/raise': typeof RaiseRoute
  '/h/$id': typeof HIdRouteWithChildren
  '/h/$id/thank': typeof HIdThankRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/raise': typeof RaiseRoute
  '/h/$id': typeof HIdRouteWithChildren
  '/h/$id/thank': typeof HIdThankRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/raise' | '/h/$id' | '/h/$id/thank'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/raise' | '/h/$id' | '/h/$id/thank'
  id: '__root__' | '/' | '/raise' | '/h/$id' | '/h/$id/thank'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RaiseRoute: typeof RaiseRoute
  HIdRoute: typeof HIdRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RaiseRoute: RaiseRoute,
  HIdRoute: HIdRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/raise",
        "/h/$id"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/raise": {
      "filePath": "raise.tsx"
    },
    "/h/$id": {
      "filePath": "h.$id.tsx",
      "children": [
        "/h/$id/thank"
      ]
    },
    "/h/$id/thank": {
      "filePath": "h.$id.thank.tsx",
      "parent": "/h/$id"
    }
  }
}
ROUTE_MANIFEST_END */
