// Regenerates app/server/og/fonts.b64.ts from app/server/og/fonts/*.ttf.
// Run from apps/web: bun scripts/generate-og-fonts.ts
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const og = join(import.meta.dir, "../app/server/og");
const fonts = {
  SG400: "SchibstedGrotesk-400.ttf",
  SG700: "SchibstedGrotesk-700.ttf",
  NS400: "NotoSans-400.ttf",
  NS700: "NotoSans-700.ttf",
};

const lines = [
  "// GENERATED by scripts/generate-og-fonts.ts — base64 of ./fonts/*.ttf,",
  "// baked into the module so the serverless bundle carries them (runtime fs",
  "// reads and bundler asset emission both fail in the vinxi server build).",
  "",
  ...Object.entries(fonts).map(
    ([name, file]) =>
      `export const ${name} = "${readFileSync(join(og, "fonts", file)).toString("base64")}";`,
  ),
];
writeFileSync(join(og, "fonts.b64.ts"), lines.join("\n") + "\n");
console.log(`fonts.b64.ts regenerated (${Object.keys(fonts).join(", ")})`);
