import { describe, expect, it } from "vitest";
import { recoverAddress, type Hex } from "viem";
import { privateKeyToAccount } from "viem/accounts";
import vectors from "./test-vectors.json";
import {
  GIVE_TYPEHASH,
  GIVER_ACCEPTANCE_TYPEHASH,
  SHAKE_TYPEHASH,
  SHAKER_ACCEPTANCE_TYPEHASH,
  ZERO_ADDRESS,
  domainSeparator,
  eip712Digest,
  fromCompactSig,
  giveDigest,
  giveHash,
  giverAcceptanceDigest,
  giverAcceptanceStructHash,
  handRef,
  routeHash,
  routeHashOf,
  shakeDigest,
  shakeStructHash,
  shakerAcceptanceDigest,
  shakerAcceptanceStructHash,
  signGive,
  signGiverAcceptance,
  signShake,
  signShakerAcceptance,
  toCompactSig,
  type Give,
  type Shake,
  type TypedSigner,
} from "../src/index.js";

/**
 * Contract-generated byte-identity suite. Every expected value in
 * test-vectors.json is emitted by contracts/test/GenVectors.t.sol straight
 * from AHandSig — the CONTRACT side is authoritative. The SDK must reproduce
 * each hash, digest and EIP-2098 compact signature byte for byte.
 *
 * Regenerate the fixture file with:
 *   cd contracts && FOUNDRY_OUT=out-vec forge test --match-path 'test/GenVectors.t.sol' -vv
 */

interface VecShakeFields {
  handId: number;
  childCapability: `0x${string}`;
  shaker: `0x${string}`;
  parentClaimBps: number;
  childClaimBps: number;
  hopDataHash: Hex;
  deadline: number;
}

interface VecAcceptance {
  signerPriv: Hex;
  signerAddr: `0x${string}`;
  structHash: Hex;
  digest: Hex;
  signatureCompact: Hex;
}

interface VecHop {
  mode: "anonymous" | "self" | "explicit";
  signerPriv: Hex;
  signerAddr: `0x${string}`;
  shake: VecShakeFields;
  shakeHash: Hex;
  shakeDigest: Hex;
  signatureCompact: Hex;
  acceptance?: VecAcceptance;
}

interface VecGive {
  give: {
    handId: number;
    routeHash: Hex;
    giver: `0x${string}`;
    solutionHash: Hex;
    finalClaimBps: number;
    deadline: number;
  };
  signerPriv: Hex;
  signerAddr: `0x${string}`;
  giveHash: Hex;
  giveDigest: Hex;
  signatureCompact: Hex;
  acceptance: VecAcceptance;
}

interface VecRoute {
  name: string;
  handId: number;
  handRef: Hex;
  shakes: VecHop[];
  routeHash: Hex;
  give: VecGive;
}

interface VecEdge {
  shake: VecShakeFields;
  shakeHash: Hex;
  shakeDigest: Hex;
}

interface Vectors {
  domain: {
    name: string;
    version: string;
    chainId: number;
    core: `0x${string}`;
    domainSeparator: Hex;
  };
  typehashes: {
    Shake: Hex;
    ShakerAcceptance: Hex;
    Give: Hex;
    GiverAcceptance: Hex;
  };
  routes: VecRoute[];
  edges: { deadlineMax: VecEdge; bpsZero: VecEdge; bpsFull: VecEdge };
}

const V = vectors as unknown as Vectors;

const CHAIN_ID = BigInt(V.domain.chainId);
const CORE = V.domain.core;
const DS = domainSeparator(CHAIN_ID, CORE);

/** Hex equality independent of EIP-55 casing (forge emits checksummed addresses). */
function eqHex(actual: string, expected: string): void {
  expect(actual.toLowerCase()).toBe(expected.toLowerCase());
}

function toShake(v: VecShakeFields): Shake {
  return {
    handId: BigInt(v.handId),
    childCapability: v.childCapability,
    shaker: v.shaker,
    parentClaimBps: v.parentClaimBps,
    childClaimBps: v.childClaimBps,
    hopDataHash: v.hopDataHash,
    deadline: BigInt(v.deadline),
  };
}

function toGive(v: VecGive["give"]): Give {
  return {
    handId: BigInt(v.handId),
    routeHash: v.routeHash,
    giver: v.giver,
    solutionHash: v.solutionHash,
    finalClaimBps: v.finalClaimBps,
    deadline: BigInt(v.deadline),
  };
}

/** Reproduce a vector signature two ways: raw digest sign + typed-data path. */
async function rawCompactSig(priv: Hex, digest: Hex): Promise<Hex> {
  const sig = await privateKeyToAccount(priv).sign({ hash: digest });
  return toCompactSig(sig);
}

describe("contract vectors: domain", () => {
  it("domain metadata matches the frozen constants", () => {
    expect(V.domain.name).toBe("aHand");
    expect(V.domain.version).toBe("2");
    expect(V.domain.chainId).toBe(31337);
  });

  it("domainSeparator matches AHandSig.domainSeparator", () => {
    eqHex(DS, V.domain.domainSeparator);
  });

  it("all four typehashes match the AHandSig constants", () => {
    eqHex(SHAKE_TYPEHASH, V.typehashes.Shake);
    eqHex(SHAKER_ACCEPTANCE_TYPEHASH, V.typehashes.ShakerAcceptance);
    eqHex(GIVE_TYPEHASH, V.typehashes.Give);
    eqHex(GIVER_ACCEPTANCE_TYPEHASH, V.typehashes.GiverAcceptance);
  });
});

describe.each(V.routes.map((r) => [r.name, r] as const))(
  "contract vectors: %s",
  (_name, route) => {
    const ref = {
      chainId: CHAIN_ID,
      core: CORE,
      handId: BigInt(route.handId),
    };
    const shakes = route.shakes.map((h) => toShake(h.shake));

    it("handRef matches AHandSig.handRef", () => {
      eqHex(handRef(ref), route.handRef);
    });

    it("shake struct hashes match AHandSig.hashShake", () => {
      route.shakes.forEach((hop, i) => {
        eqHex(shakeStructHash(shakes[i]), hop.shakeHash);
      });
    });

    it("shake digests match on both the typed-data and the 1901 path", () => {
      route.shakes.forEach((hop, i) => {
        eqHex(shakeDigest(shakes[i], CHAIN_ID, CORE), hop.shakeDigest);
        eqHex(eip712Digest(DS, hop.shakeHash), hop.shakeDigest);
      });
    });

    it("shake signatures reproduce byte-identically (raw + signTypedData)", async () => {
      for (const [i, hop] of route.shakes.entries()) {
        eqHex(await rawCompactSig(hop.signerPriv, hop.shakeDigest), hop.signatureCompact);
        const typed = await signShake(shakes[i], hop.signerPriv, CHAIN_ID, CORE);
        eqHex(toCompactSig(typed), hop.signatureCompact);
      }
    });

    it("shake signatures recover the parent capability", async () => {
      for (const hop of route.shakes) {
        const long = fromCompactSig(hop.signatureCompact);
        expect(long.length).toBe(132);
        const rec = await recoverAddress({ hash: hop.shakeDigest, signature: long });
        eqHex(rec, hop.signerAddr);
        // EIP-2098 round-trip is lossless.
        eqHex(toCompactSig(long), hop.signatureCompact);
      }
    });

    it("hop modes carry the frozen shaker semantics", () => {
      route.shakes.forEach((hop, i) => {
        if (i > 0) {
          // Telescoping: parentClaim restates the previous hop's childClaim.
          expect(hop.shake.parentClaimBps).toBe(route.shakes[i - 1].shake.childClaimBps);
        }
        if (hop.mode === "anonymous") {
          eqHex(hop.shake.shaker, ZERO_ADDRESS);
          expect(hop.shake.parentClaimBps).toBe(hop.shake.childClaimBps); // zero-margin only
          expect(hop.acceptance).toBeUndefined();
        } else if (hop.mode === "self") {
          eqHex(hop.shake.shaker, hop.signerAddr); // shaker IS the signing parent capability
          expect(hop.acceptance).toBeUndefined();
        } else {
          expect(hop.acceptance).toBeDefined();
          eqHex(hop.acceptance!.signerAddr, hop.shake.shaker); // consent by the attributed wallet
        }
      });
    });

    it("shaker acceptances match hash, digest and signature", async () => {
      for (const hop of route.shakes) {
        if (!hop.acceptance) continue;
        const acc = hop.acceptance;
        eqHex(shakerAcceptanceStructHash(hop.shakeHash), acc.structHash);
        eqHex(shakerAcceptanceDigest(hop.shakeHash, CHAIN_ID, CORE), acc.digest);
        eqHex(eip712Digest(DS, acc.structHash), acc.digest);
        eqHex(await rawCompactSig(acc.signerPriv, acc.digest), acc.signatureCompact);
        const typed = await signShakerAcceptance(
          hop.shakeHash,
          privateKeyToAccount(acc.signerPriv) as TypedSigner,
          CHAIN_ID,
          CORE,
        );
        eqHex(toCompactSig(typed), acc.signatureCompact);
      }
    });

    it("routeHash matches AHandSig.hashRoute (struct hashes only, no sig bytes)", () => {
      eqHex(routeHash(route.handRef, route.shakes.map((h) => h.shakeHash)), route.routeHash);
      eqHex(routeHashOf(ref, shakes), route.routeHash);
      eqHex(route.give.give.routeHash, route.routeHash); // Give binds the complete route
    });

    it("give hash, digest and signature reproduce", async () => {
      const g = toGive(route.give.give);
      eqHex(giveHash(g), route.give.giveHash);
      eqHex(giveDigest(g, CHAIN_ID, CORE), route.give.giveDigest);
      eqHex(eip712Digest(DS, route.give.giveHash), route.give.giveDigest);
      eqHex(
        await rawCompactSig(route.give.signerPriv, route.give.giveDigest),
        route.give.signatureCompact,
      );
      const typed = await signGive(g, route.give.signerPriv, CHAIN_ID, CORE);
      eqHex(toCompactSig(typed), route.give.signatureCompact);
      const rec = await recoverAddress({
        hash: route.give.giveDigest,
        signature: fromCompactSig(route.give.signatureCompact),
      });
      eqHex(rec, route.give.signerAddr); // the LAST capability of the route signs
    });

    it("giver acceptance matches hash, digest and signature", async () => {
      const acc = route.give.acceptance;
      eqHex(giverAcceptanceStructHash(route.give.giveHash), acc.structHash);
      eqHex(giverAcceptanceDigest(route.give.giveHash, CHAIN_ID, CORE), acc.digest);
      eqHex(acc.signerAddr, route.give.give.giver); // consent by the attributed giver wallet
      eqHex(await rawCompactSig(acc.signerPriv, acc.digest), acc.signatureCompact);
      const typed = await signGiverAcceptance(
        route.give.giveHash,
        privateKeyToAccount(acc.signerPriv) as TypedSigner,
        CHAIN_ID,
        CORE,
      );
      eqHex(toCompactSig(typed), acc.signatureCompact);
    });
  },
);

describe("contract vectors: route fixture shape", () => {
  it("covers zero-hop, one-hop self and six-hop mixed", () => {
    expect(V.routes.map((r) => [r.name, r.shakes.length])).toEqual([
      ["zero_hop", 0],
      ["one_hop_self", 1],
      ["six_hop_mixed", 6],
    ]);
    // Zero-hop: root capability signs the Give over the empty route at full claim.
    expect(V.routes[0].give.give.finalClaimBps).toBe(10_000);
    // Six-hop: anonymous / self / explicit alternate through the route.
    expect(V.routes[2].shakes.map((h) => h.mode)).toEqual([
      "anonymous", "self", "explicit", "anonymous", "self", "explicit",
    ]);
  });
});

describe("contract vectors: edge scalars", () => {
  const cases = [
    ["deadlineMax", V.edges.deadlineMax],
    ["bpsZero", V.edges.bpsZero],
    ["bpsFull", V.edges.bpsFull],
  ] as const;

  it.each(cases)("%s shake hash and digest reproduce", (name, edge) => {
    const s = toShake(edge.shake);
    eqHex(shakeStructHash(s), edge.shakeHash);
    eqHex(shakeDigest(s, CHAIN_ID, CORE), edge.shakeDigest);
    eqHex(eip712Digest(DS, edge.shakeHash), edge.shakeDigest);
    if (name === "deadlineMax") {
      expect(edge.shake.deadline).toBe(2 ** 40 - 1); // uint40 max, exact in a JSON number
    }
    if (name === "bpsZero") {
      expect(edge.shake.parentClaimBps).toBe(0);
      expect(edge.shake.childClaimBps).toBe(0);
    }
    if (name === "bpsFull") {
      expect(edge.shake.parentClaimBps).toBe(10_000);
      expect(edge.shake.childClaimBps).toBe(10_000);
    }
  });
});
