// SPDX-License-Identifier: MIT
pragma solidity 0.8.35;

import "forge-std/Test.sol";
import {AHandSig, Shake, Give} from "../src/AHandTypes.sol";

/*//////////////////////////////////////////////////////////////
            Contract-authoritative EIP-712 test vectors
//////////////////////////////////////////////////////////////*/

/// @notice Generates packages/sdk/tests/test-vectors.json — the byte-identity
///         oracle the SDK hashing/signing suite replays. Everything is pinned:
///         chain id 31337 (vm.chainId), a fixed core address and the well-known
///         anvil mnemonic keys, so the output is environment-independent and
///         the file only changes when AHandSig itself changes.
///
///         Regenerate:
///           cd contracts && FOUNDRY_OUT=out-vec forge test --match-path 'test/GenVectors.t.sol' -vv
contract GenVectorsTest is Test {
    uint256 internal constant CHAIN_ID = 31337;
    /// @dev Deliberately not a deployed contract: AHandSig.domainSeparator takes
    ///      the core address as an explicit parameter, so vectors bind a fixed
    ///      address instead of an environment-dependent deployment address.
    address internal constant CORE = 0x00c0FFeE00C0ffEE00C0FfeE00c0fFEe00C0ffEE;

    string internal constant OUT_PATH = "../packages/sdk/tests/test-vectors.json";

    // Well-known anvil keys (accounts 0..9 of the default mnemonic).
    uint256 internal constant PK_ROOT = 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80; // [0]
    uint256 internal constant PK_CAP1 = 0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d; // [1]
    uint256 internal constant PK_CAP2 = 0x5de4111afa1a4b94908f83103eb1f1706367c2e68ca870fc3fb9a804cdab365a; // [2]
    uint256 internal constant PK_CAP3 = 0x7c852118294e51e653712a81e05800f419141751be58f605c371e15141b007a6; // [3]
    uint256 internal constant PK_CAP4 = 0x47e179ec197488593b187f80a00eb0da91f1b9d0b13f8733639f19c30a34926a; // [4]
    uint256 internal constant PK_CAP5 = 0x8b3a350cf5c34c9194ca85829a2df0ec3153be0318b5e2d3348e872092edffba; // [5]
    uint256 internal constant PK_CAP6 = 0x92db14e403b83dfe3df233f83dfa3a0d7096f21ca9b0d6d6b8d88b2b4ec1564e; // [6]
    uint256 internal constant PK_SHAKER_A = 0x4bbbf85ce3377467afe5d46f804f221813b2bb87f24d81f60f1fcdbf7cbf4356; // [7]
    uint256 internal constant PK_SHAKER_B = 0xdbda1821b80551c9d65939329250298aa3472ba22feea921c0cf5d620ea67b97; // [8]
    uint256 internal constant PK_GIVER = 0x2a871d0798f97d79848a013d4936a73bf4cc922c825d33c1cf7073dff6d409c6; // [9]

    bytes32 internal ds; // domain separator under CHAIN_ID + CORE

    function test_GenerateVectors() public {
        vm.chainId(CHAIN_ID);
        ds = AHandSig.domainSeparator(CORE);
        assertTrue(ds != bytes32(0), "domain separator");

        string memory json = string.concat(
            '{"_comment":"Generated by contracts/test/GenVectors.t.sol - contract side is authoritative, do not edit by hand.",',
            '"domain":', domainJson(),
            ',"typehashes":', typehashesJson(),
            ',"routes":[', zeroHopJson(), ",", oneHopSelfJson(), ",", sixHopMixedJson(),
            '],"edges":', edgesJson(),
            "}"
        );
        vm.writeJson(json, OUT_PATH);
    }

    /*//////////////////////////////////////////////////////////////
                                Fixtures
    //////////////////////////////////////////////////////////////*/

    /// Zero-hop: no shakes, root capability signs the Give, finalClaim 10000.
    function zeroHopJson() internal returns (string memory) {
        uint256 handId = 1;
        bytes32 ref = AHandSig.handRef(CORE, handId);
        bytes32 rh = AHandSig.hashRoute(ref, new bytes32[](0));
        Give memory g = Give({
            handId: handId,
            routeHash: rh,
            giver: vm.addr(PK_GIVER),
            solutionHash: keccak256("aHand/vectors/solution/zero-hop"),
            finalClaimBps: 10_000,
            deadline: 2_000_000_000
        });
        return string.concat(
            '{"name":"zero_hop","handId":', vm.toString(handId),
            ',"handRef":"', vm.toString(ref),
            '","shakes":[],"routeHash":"', vm.toString(rh),
            '","give":', giveJson(g, PK_ROOT, PK_GIVER),
            "}"
        );
    }

    /// One hop in self mode: shaker == the parent capability that signed the Shake.
    function oneHopSelfJson() internal returns (string memory) {
        uint256 handId = 2;
        bytes32 ref = AHandSig.handRef(CORE, handId);
        Shake memory s = Shake({
            handId: handId,
            childCapability: vm.addr(PK_CAP1),
            shaker: vm.addr(PK_ROOT), // self mode
            parentClaimBps: 10_000,
            childClaimBps: 9_000,
            hopDataHash: keccak256("aHand/vectors/hop-data/one-hop"),
            deadline: 2_000_000_000
        });
        (string memory hop, bytes32 sh) = hopJson("self", s, PK_ROOT, 0);
        bytes32[] memory hashes = new bytes32[](1);
        hashes[0] = sh;
        bytes32 rh = AHandSig.hashRoute(ref, hashes);
        Give memory g = Give({
            handId: handId,
            routeHash: rh,
            giver: vm.addr(PK_GIVER),
            solutionHash: keccak256("aHand/vectors/solution/one-hop"),
            finalClaimBps: 9_000,
            deadline: 2_000_000_000
        });
        return string.concat(
            '{"name":"one_hop_self","handId":', vm.toString(handId),
            ',"handRef":"', vm.toString(ref),
            '","shakes":[', hop,
            '],"routeHash":"', vm.toString(rh),
            '","give":', giveJson(g, PK_CAP1, PK_GIVER),
            "}"
        );
    }

    /// Six hops alternating anonymous / self / explicit. Anonymous hops carry
    /// zero margin (parent == child); explicit hops carry ShakerAcceptances.
    function sixHopMixedJson() internal returns (string memory) {
        uint256 handId = 3;
        bytes32 ref = AHandSig.handRef(CORE, handId);
        uint256[7] memory caps = [PK_ROOT, PK_CAP1, PK_CAP2, PK_CAP3, PK_CAP4, PK_CAP5, PK_CAP6];
        uint16[6] memory parentBps = [uint16(10_000), 10_000, 9_000, 8_000, 8_000, 7_000];
        uint16[6] memory childBps = [uint16(10_000), 9_000, 8_000, 8_000, 7_000, 6_000];
        address[6] memory shakers = [
            address(0), vm.addr(PK_CAP1), vm.addr(PK_SHAKER_A),
            address(0), vm.addr(PK_CAP4), vm.addr(PK_SHAKER_B)
        ];
        uint256[6] memory acceptPks = [uint256(0), 0, PK_SHAKER_A, 0, 0, PK_SHAKER_B];
        bytes32[6] memory hopData = [
            bytes32(0), keccak256("aHand/vectors/hop-data/six-hop/2"), bytes32(0),
            keccak256("aHand/vectors/hop-data/six-hop/4"), bytes32(0), keccak256("aHand/vectors/hop-data/six-hop/6")
        ];
        string[6] memory modes = ["anonymous", "self", "explicit", "anonymous", "self", "explicit"];

        bytes32[] memory hashes = new bytes32[](6);
        string memory shakes = "";
        for (uint256 i = 0; i < 6; i++) {
            Shake memory s = Shake({
                handId: handId,
                childCapability: vm.addr(caps[i + 1]),
                shaker: shakers[i],
                parentClaimBps: parentBps[i],
                childClaimBps: childBps[i],
                hopDataHash: hopData[i],
                deadline: uint40(1_990_000_000 + i * 100)
            });
            (string memory hop, bytes32 sh) = hopJson(modes[i], s, caps[i], acceptPks[i]);
            hashes[i] = sh;
            shakes = i == 0 ? hop : string.concat(shakes, ",", hop);
        }
        bytes32 rh = AHandSig.hashRoute(ref, hashes);
        Give memory g = Give({
            handId: handId,
            routeHash: rh,
            giver: vm.addr(PK_GIVER),
            solutionHash: keccak256("aHand/vectors/solution/six-hop"),
            finalClaimBps: 6_000,
            deadline: 1_990_000_600
        });
        return string.concat(
            '{"name":"six_hop_mixed","handId":', vm.toString(handId),
            ',"handRef":"', vm.toString(ref),
            '","shakes":[', shakes,
            '],"routeHash":"', vm.toString(rh),
            '","give":', giveJson(g, PK_CAP6, PK_GIVER),
            "}"
        );
    }

    /// Edge scalars: uint40 deadline at its maximum, bps at 0 and at 10000.
    function edgesJson() internal view returns (string memory) {
        Shake memory dmax = Shake({
            handId: 7,
            childCapability: vm.addr(PK_CAP1),
            shaker: address(0),
            parentClaimBps: 10_000,
            childClaimBps: 10_000,
            hopDataHash: bytes32(0),
            deadline: type(uint40).max
        });
        Shake memory bz = Shake({
            handId: 8,
            childCapability: vm.addr(PK_CAP1),
            shaker: address(0),
            parentClaimBps: 0,
            childClaimBps: 0,
            hopDataHash: bytes32(0),
            deadline: 2_000_000_000
        });
        Shake memory bf = Shake({
            handId: 9,
            childCapability: vm.addr(PK_CAP1),
            shaker: address(0),
            parentClaimBps: 10_000,
            childClaimBps: 10_000,
            hopDataHash: bytes32(0),
            deadline: 2_000_000_000
        });
        return string.concat(
            '{"deadlineMax":', edgeEntry(dmax),
            ',"bpsZero":', edgeEntry(bz),
            ',"bpsFull":', edgeEntry(bf),
            "}"
        );
    }

    /*//////////////////////////////////////////////////////////////
                            JSON builders
    //////////////////////////////////////////////////////////////*/

    function domainJson() internal view returns (string memory) {
        return string.concat(
            '{"name":"aHand","version":"2","chainId":', vm.toString(CHAIN_ID),
            ',"core":"', vm.toString(CORE),
            '","domainSeparator":"', vm.toString(ds),
            '"}'
        );
    }

    function typehashesJson() internal pure returns (string memory) {
        return string.concat(
            '{"Shake":"', vm.toString(AHandSig.SHAKE_TYPEHASH),
            '","ShakerAcceptance":"', vm.toString(AHandSig.SHAKER_ACCEPTANCE_TYPEHASH),
            '","Give":"', vm.toString(AHandSig.GIVE_TYPEHASH),
            '","GiverAcceptance":"', vm.toString(AHandSig.GIVER_ACCEPTANCE_TYPEHASH),
            '"}'
        );
    }

    function shakeJson(Shake memory s) internal pure returns (string memory) {
        return string.concat(
            '{"handId":', vm.toString(s.handId),
            ',"childCapability":"', vm.toString(s.childCapability),
            '","shaker":"', vm.toString(s.shaker),
            '","parentClaimBps":', vm.toString(s.parentClaimBps),
            ',"childClaimBps":', vm.toString(s.childClaimBps),
            ',"hopDataHash":"', vm.toString(s.hopDataHash),
            '","deadline":', vm.toString(s.deadline),
            "}"
        );
    }

    /// One route hop: the Shake struct, its hash/digest and the parent-capability
    /// signature; explicit hops additionally carry the ShakerAcceptance artifact.
    function hopJson(string memory mode, Shake memory s, uint256 signerPk, uint256 acceptPk)
        internal
        returns (string memory, bytes32)
    {
        bytes32 sh = AHandSig.hashShake(s);
        bytes32 d = AHandSig.digest(ds, sh);
        string memory acc = "";
        if (acceptPk != 0) {
            acc = string.concat(',"acceptance":', acceptanceJson(AHandSig.hashShakerAcceptance(sh), acceptPk));
        }
        string memory j = string.concat(
            '{"mode":"', mode,
            '","signerPriv":"', vm.toString(bytes32(signerPk)),
            '","signerAddr":"', vm.toString(vm.addr(signerPk)),
            '","shake":', shakeJson(s),
            ',"shakeHash":"', vm.toString(sh),
            '","shakeDigest":"', vm.toString(d),
            '","signatureCompact":"', compactSig(signerPk, d),
            '"', acc, "}"
        );
        return (j, sh);
    }

    function giveJson(Give memory g, uint256 signerPk, uint256 giverPk) internal returns (string memory) {
        bytes32 gh = AHandSig.hashGive(g);
        bytes32 d = AHandSig.digest(ds, gh);
        return string.concat(
            '{"give":{"handId":', vm.toString(g.handId),
            ',"routeHash":"', vm.toString(g.routeHash),
            '","giver":"', vm.toString(g.giver),
            '","solutionHash":"', vm.toString(g.solutionHash),
            '","finalClaimBps":', vm.toString(g.finalClaimBps),
            ',"deadline":', vm.toString(g.deadline),
            '},"signerPriv":"', vm.toString(bytes32(signerPk)),
            '","signerAddr":"', vm.toString(vm.addr(signerPk)),
            '","giveHash":"', vm.toString(gh),
            '","giveDigest":"', vm.toString(d),
            '","signatureCompact":"', compactSig(signerPk, d),
            '","acceptance":', acceptanceJson(AHandSig.hashGiverAcceptance(gh), giverPk),
            "}"
        );
    }

    /// Shared shape for ShakerAcceptance and GiverAcceptance artifacts — the
    /// caller picks the struct hash, the wallet key signs the derived digest.
    function acceptanceJson(bytes32 structHash, uint256 pk) internal returns (string memory) {
        bytes32 d = AHandSig.digest(ds, structHash);
        return string.concat(
            '{"signerPriv":"', vm.toString(bytes32(pk)),
            '","signerAddr":"', vm.toString(vm.addr(pk)),
            '","structHash":"', vm.toString(structHash),
            '","digest":"', vm.toString(d),
            '","signatureCompact":"', compactSig(pk, d),
            '"}'
        );
    }

    function edgeEntry(Shake memory s) internal view returns (string memory) {
        bytes32 sh = AHandSig.hashShake(s);
        return string.concat(
            '{"shake":', shakeJson(s),
            ',"shakeHash":"', vm.toString(sh),
            '","shakeDigest":"', vm.toString(AHandSig.digest(ds, sh)),
            '"}'
        );
    }

    /// EIP-2098 compact signature (r || yParityAndS), sanity-checked by ecrecover.
    function compactSig(uint256 pk, bytes32 d) internal returns (string memory) {
        (uint8 v, bytes32 r, bytes32 s) = vm.sign(pk, d);
        assertEq(ecrecover(d, v, r, s), vm.addr(pk), "signature sanity");
        return vm.toString(abi.encodePacked(r, bytes32(uint256(s) | (uint256(v - 27) << 255))));
    }
}
